apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: server
  namespace: default
spec:
  components:
    - name: server
      type: webservice
      properties:
        image: demo.goharbor.io/gxr/nginx:1
