apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  components:
    - name: my-server
      type: webservice
      properties:
        image: harbor.cloud2go.cn/test/nginx:1
        port: 80
  workflow:
    steps:
      - name: apply-server
        type: apply-component
        properties: 
          component: my-server
        outputs:
          - name: server-status
            valueFrom: output.spec.template.spec.containers[0].image + " image applied."
